### ISSUE TITLE
Why HuggingFace file is inaccessible?

### ISSUE THREAD

**Issue by zhimin-z** [OpenKG-ORG/openkg-org.github.io#1]
https://huggingface.co/spaces/openkg/llm_leaderboard
![image](https://github.com/OpenKG-ORG/openkg-org.github.io/assets/8592144/3b7d2b16-2ada-4005-98cd-d1c4f56129c5)

**Comment by zxlzr** [comment]
您好我这里显示可以正常访问。
<img width="1087" alt="image" src="https://github.com/OpenKG-ORG/openkg-org.github.io/assets/1264492/b2ea1d15-faa7-4417-be61-715e9f1cfaeb">

**Comment by zhimin-z** [comment]
> 您好我这里显示可以正常访问。 <img alt="image" width="1087" src="https://user-images.githubusercontent.com/1264492/284018636-b2ea1d15-faa7-4417-be61-715e9f1cfaeb.png">

Are you clicking this button with a third-party account?
![image](https://github.com/OpenKG-ORG/openkg-org.github.io/assets/8592144/763a8820-044e-4f30-aa5c-c39e54422c5b)

**Comment by zxlzr** [comment]
We have  found this is a  bug in Huggingface, we are trying to fix it soon.

**Comment by zxlzr** [comment]
Sorry, we recently found HF do not contain enough resources for running our leaderboard, so we are migrating to other platforms. We will release the new llm_leaderboard soon. Sorry for your inconvenience.

**Comment by zhimin-z** [comment]
> Sorry, we recently found HF do not contain enough resources for running our leaderboard, so we are migrating to other platforms. We will release the new llm_leaderboard soon. Sorry for your inconvenience.

Thanks for your reply. which platform do you plan to migrate to?

**Comment by zxlzr** [comment]
> > Sorry, we recently found HF do not contain enough resources for running our leaderboard, so we are migrating to other platforms. We will release the new llm_leaderboard soon. Sorry for your inconvenience.
> 
> Thanks for your reply. which platform do you plan to migrate to?

We will build a new website on Aliyun for OpenKG-LLM evaluation in the next few month.
