### ISSUE TITLE
HuggingFace app is boken 

### ISSUE THREAD

**Issue by zhimin-z** [OpenKG-ORG/openkg-org.github.io#2]
https://huggingface.co/spaces/openkg/llm_leaderboard/discussions/4

**Comment by zxlzr** [comment]
Sorry, we recently found HF do not contain enough resources for running our leaderboard, so we are migrating to other platforms. We will release the new llm_leaderboard soon. Sorry for your inconvenience.

**Comment by zhimin-z** [comment]
> Sorry, we recently found HF do not contain enough resources for running our leaderboard, so we are migrating to other platforms. We will release the new llm_leaderboard soon. Sorry for your inconvenience.

Which platform do you plan to migrate to?
